### ISSUE TITLE
npm ERR! missing script: gh-pages-deploy

### ISSUE THREAD

**Issue by ryanjones97** [Rolanddoda/vue-cli-plugin-gh-pages-auto-deploy#11]
Getting `npm ERR! missing script: gh-pages-deploy` when I push to master any ideas?

**Comment by Rolanddoda** [comment]
@rynjnes can you please share your repo or add more details so I can get a better understanding on why you get the error? Or connect with me on [Linkedin](https://www.linkedin.com/in/roland-doda/) and let's have a conversation there.

**Comment by Rolanddoda** [comment]
@rynjnes from what I saw, you didn't install this plugin quite right. But you gave me access to your repo, I installed it correctly, and your site is live 🎉

**Comment by ryanjones97** [comment]
Thanks for your help really appreciate it :)
