### ISSUE TITLE
Installting package fails

### ISSUE THREAD

**Issue by deathwebo** [Rolanddoda/vue-cli-plugin-gh-pages-auto-deploy#4]
Hello 👋. I'm trying to use the package in my project to deploy my vue 3 app, created with vue cli. 

Running the installation command `vue add gh-pages-auto-deploy` I get this:

```
⚓  Running completion hooks...
 ERROR  Error: Command failed with ENOENT: vue-cli-service lint
spawn vue-cli-service ENOENT
Error: Command failed with ENOENT: vue-cli-service lint
spawn vue-cli-service ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**Comment by Rolanddoda** [comment]
Hi @deathwebo thanks for filling an issue.

From the error I see that you have eslint errors. If you fix those errors everything should be working fine. To see eslint errors you can run `npm run lint` in your project.
